### ISSUE TITLE
Failed Ajax request or invalid JSON returned

### ISSUE THREAD

**Issue by johanesmikhael** [pkp/paperbuzz#12]
Dear All,
I tried to integrate this plugin to our website with OJS 3.1.1.4 and with bootstrap3-v1.1.4. I put some modification on article pages template by using bootstrap child-theme. I got Failed Ajax request or invalid JSON returned when I clicked "setting" button in plugin management page. Is the plugin only works with default theme?

**Comment by asmecher** [comment]
@johanesmikhael, have you tried using your browser's inspection tools to see what the AJAX response looks like (the one that is causing the error message)?

**Comment by johanesmikhael** [comment]
Dear @asmecher , It looks this in console editor on browser's inspection:

`(Internal Server Error)`
`send @ jquery.min.js:4`
`ajax @ jquery.min.js:4`
`a.fn.pkpAjaxHtml @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.controllers.modal.AjaxModalHandler.modalOpen @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.controllers.modal.ModalHandler @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.classes.ObjectProxy.parent @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.controllers.modal.AjaxModalHandler @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.classes.ObjectProxy.parent @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.classes.Helper.objectFactory @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:`
`(anonymous) @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`each @ jquery.min.js:2`
`each @ jquery.min.js:2`
`a.fn.pkpHandler @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.classes.linkAction.ModalRequest.activate @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.controllers.linkAction.LinkActionHandler.activateAction @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`a.pkp.classes.Handler.handleEvent @ pkp.min.js.pagespeed.jm.ucbpU_7C6l.js:1`
`dispatch @ jquery.min.js:3`
`r.handle @ jquery.min.js:3`

Does it mean something to do with jquery? I am bit confused. Thank you so much with your response,

**Comment by asmecher** [comment]
The `Internal Server Error` suggests a server-side problem; is there anything on your server's PHP error log?

**Comment by asmecher** [comment]
Closing as outdated.
