### ISSUE TITLE
Feature request: show abstract view metrics!

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [pkp/paperbuzz#2]
We are using ALM to display metrics from the locally collected usage statistics. 
This displays PDF downloads aka full-text views really nicely!

Is it possible to show abstract views as well?

I guess this needs some coding but if someone gives me a direction where to start (or provide me with documentation) I might be able to come up with something myself...

Greetings
Hermann

**Comment by NateWr** [comment]
Closing as outdated.
