### ISSUE TITLE
Plugin error prevents submission and issue previews in later versions of 3.3 LTS

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/paperbuzz#31]
Only mentioning this because 3.3 is the LTS. In 3.3.0.14 and 3.3.0.15, the plugin affects previews for issues and submissions. In 3.3.0.14, submission previews are missing galleys and most of the metadata; in 3.3.0.15, submission previews return a 500 error. Issue previews do not include submissions scheduled for that issue. Disabling the plugin resolves the problem.

My IT support checked the PHP error logs and tells me the error because the plugin calls a method that no longer exists.

**Comment by asmecher** [comment]
@tmrozewski-york, do you have the details (ideally the PHP error message)?

**Comment by tmrozewski-york** [comment]
@asmecher have asked my IT support to provide, stay tuned.

**Comment by ajntc** [comment]
I can share some details about this error:
```
Fatal error: Uncaught Error: Call to undefined method Submission::getIssueId() in /var/www/ojs/plugins/generic/paperbuzz/PaperbuzzPlugin.inc.php:355 
Stack trace: 
#0 /var/www/ojs/plugins/generic/paperbuzz/PaperbuzzPlugin.inc.php(317): PaperbuzzPlugin->_getDownloadStats(true) 
#1 /var/www/ojs/lib/pkp/classes/cache/GenericCache.inc.php(63): PaperbuzzPlugin->_downloadsCacheMiss(Object(FileCache), NULL) 
#2 /var/www/ojs/lib/pkp/classes/cache/FileCache.inc.php(125): GenericCache->get(NULL) 
#3 /var/www/ojs/plugins/generic/paperbuzz/PaperbuzzPlugin.inc.php(305): FileCache->getContents() 
#4 /var/www/ojs/plugins/generic/paperbuzz/PaperbuzzPlugin.inc.php(220): PaperbuzzPlugin->_getDownloadsJsonDecoded() 
#5 /var/www/ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): PaperbuzzPlugin->articleMainCallback('Templates::Arti...', Array) 
#6 /var/www/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1540): HookRegistry::call('Templates::Arti...', Array) 
#7 /var/www/ojs/cache/t_compile/93b4f13326abf2c920de729fdcdace1580d9bcb7^addd6502 in /var/www/ojs/plugins/generic/paperbuzz/PaperbuzzPlugin.inc.php on line 355
```
As you can see it calls ` undefined method Submission::getIssueId()` and the page crashes.

**Comment by ajntc** [comment]
@asmecher We have recently (about a week ago) updated our OJS from 3.3.0-13 to 3.3.0-15, and today during our tests of  QuickSubmitPlugin this error occurred in one of articles added that way.

**Comment by asmecher** [comment]
@ajntc / @tmrozewski-york, can you confirm that applying https://github.com/pkp/paperbuzz/commit/c1199260c05edc1a81c31c3b7a3e56c57255b3b8 in `plugins/generic/paperbuzz` resolves the issue?

**Comment by ajntc** [comment]
Yes, I can confirm it fixed the issue. 
@tmrozewski-york - what about you?

**Comment by tmrozewski-york** [comment]
I haven't had the opportunity to pass it on to my IT support but will shortly and will let you know.

**Comment by asmecher** [comment]
Another confirmation would be great, but I'll go ahead and close this issue for now! This should be included in the next release of the Paperbuzz plugin for OJS 3.3.0-x.

**Comment by tmrozewski-york** [comment]
@asmecher I'm told by my IT support that this patch _didn't_ fix it for us. From the log:

`[Thu Sep 28 15:29:36.921956 2023] [php7:error] [pid 4152489] [client 149.115.64.156:60081] PHP Fatal error:  Uncaught Error: Call to a member function getData() on bool in /var/www/refuge.journals.yorku.ca/ojs/plugins/generic/paperbuzz/PaperbuzzPlugin.inc.php:227\nStack trace:\n#0 /var/www/refuge.journals.yorku.ca/ojs/lib/pkp/classes/plugins/HookRegistry.inc.php(107): PaperbuzzPlugin->articleMainCallback()\n#1 /var/www/refuge.journals.yorku.ca/ojs/lib/pkp/classes/template/PKPTemplateManager.inc.php(1540): HookRegistry::call()\n#2 /var/www/refuge.journals.yorku.ca/ojs/cache/t_compile/42362804174f266c598cdb32c3208fc745b92101^addd65021fadf964339ab08cd1aa93ba59b14e9c_0.app.frontendobjectsarticle_details.tpl.php(188): PKPTemplateManager->smartyCallHook()\n#3 /var/www/refuge.journals.yorku.ca/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6515d35125f450_59027403()\n#4 /var/www/refuge.journals.yorku.ca/ojs/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()\n#5 /var/www/refuge.journals.yor in /var/www/refuge.journals.yorku.ca/ojs/plugins/generic/paperbuzz/PaperbuzzPlugin.inc.php on line 227, referer: https://refuge.journals.yorku.ca/index.php/refuge/workflow/index/41212/5`

**Comment by bozana** [comment]
Hi @tmrozewski-york, I can reproduce the error -- it happens when the article is not published yet, when previewing it...
I'll take a look and fix it. 
I will let you know once I release the new plugin version with that fix...

**Comment by tmrozewski-york** [comment]
Thanks @bozana - that's exactly it, it's the preview when Paperbuzz is active that's the problem. I appreciate your attention to it.

**Comment by bozana** [comment]
@tmrozewski-york, the new plugin release is there, it can be installed via plugin gallery.

**Comment by tmrozewski-york** [comment]
Got it, thanks!
