### ISSUE TITLE
Statistics Labels language in Reader interface are not changing from primary locale

### ISSUE THREAD

**Issue by israelcefrin** [pkp/paperbuzz#8]
Hello, 

The labels of HTML or PDF view don't change the locale text when you change the Reader interface language via the "Toggle Language Block". It remains with primary locale, while all the journal switches it.

To reproduce this issue:

Dashboard > Settings > Website > Locale

Add a second language and set it as "Primary Locale"

Then go to:
Dashboard > Settings > Website > Plugins > Install PaperBuzz and enable it

Go to Reader interface, in any Article and switch the language. The Article Download Statistics section will keep the Primary Locale texts.

**Comment by diegoeffects** [comment]
Hi all,

Here for same issue. In our case We have Spanish as primary language and Ensligsh as second.

We're preparing OJS 3.3.0-14 version to migrate and found this issue, any suggestion?
